//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by Line.rc
//
#define IDD_LINE_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDB_MIGGREEN_OFF                129
#define IDB_MIGGREEN_ON                 130
#define IDB_MIGSIGNAL_OFF               131
#define IDB_MIGSIGNAL_ON                132
#define IDR_MENUFLOATINGFILE            135
#define IDD_REPAROL_DLG                 136
#define IDD_PAROL_DLG                   137
#define IDD_SAVEAS_DLG                  138
#define IDD_TREE_DLG                    139
#define IDR_MENUFLOATINGTEST            140
#define IDI_LEVEL1                      141
#define IDI_LEVEL2                      142
#define IDI_SELECT                      143
#define IDD_ADD_TREE_DLG                144
#define IDB_ADDTREE                     146
#define IDB_ADDTREEFROMMEMORY           146
#define IDB_BITMAP_DIOD                 148
#define IDB_BITMAP_RES                  149
#define IDB_BITMAP_NPN                  150
#define IDB_BITMAP_PNP                  151
#define IDB_BITMAP_PNP4                 152
#define IDB_BITMAP_NPN4                 153
#define IDB_BITMAP_NMOS                 154
#define IDB_BITMAP_NMOS4                155
#define IDB_BITMAP_PMOS                 156
#define IDB_BITMAP_PMOS4                157
#define IDB_BITMAP_DIOD_ON              162
#define IDB_BITMAP_NMOS_ON              163
#define IDB_BITMAP_NMOS4_ON             164
#define IDB_BITMAP_NPN_ON               165
#define IDB_BITMAP_PMOS_ON              166
#define IDB_BITMAP_PMOS4_ON             167
#define IDB_BITMAP_PNP_ON               168
#define IDB_BITMAP_PNP4_ON              169
#define IDB_BITMAP_RES_ON               170
#define IDB_BITMAP_NPN4_ON              171
#define IDI_ICON_AC                     172
#define IDI_ICON_IMPNEGATIVE            173
#define IDI_ICON_IMPPOSITIVE            174
#define IDI_ICONRADIO1                  175
#define IDI_ICONRADIO2                  176
#define IDB_BITMAP_U                    177
#define IDB_BITMAP_I                    178
#define IDI_ICON_NULL_LEFT              179
#define IDI_ICON_NULL_CENTER            180
#define IDI_ICON_NULL_RIGHT             181
#define IDI_ICON_BUTTON_OFF             182
#define IDI_ICON_BUTTON_ON              183
#define IDI_ICON_INVERSION_XY           184
#define IDI_ICON_MARKER_RESET           185
#define IDI_ICON_MARKER1                186
#define IDI_ICON_MARKER2                187
#define IDI_ICON_MARKER_LEFT            188
#define IDI_ICON_MARKER_RIGHT           189
#define IDI_ICON_MARKER1_ON             190
#define IDI_ICON_MARKER2_ON             191
#define IDR_MENUFLOATINGPANEL           200
#define IDR_MENUFLOATINGTUNING          200
#define IDR_MENUFLOATINGOTCHT           201
#define IDD_PART_DLG                    202
#define IDR_MENUFLOATINGGRAF            203
#define IDR_MENUFLOATINGMEMORY          204
#define IDD_ADD_TREEFROMPANEL           205
#define IDB_ADDTREEFROMPANEL            206
#define IDB_DIOD                        207
#define IDB_RES                         208
#define IDB_NPN                         209
#define IDB_PNP                         210
#define IDB_NMOS                        211
#define IDB_PMOS4                       212
#define IDB_PMOS                        212
#define IDB_NPN_4                       213
#define IDB_PNP_4                       214
#define IDB_NMOS_4                      215
#define IDB_PMOS_4                      216
#define IDB_KOL_OFF                     217
#define IDB_KOL_ON                      218
#define IDB_KOL_BAZA                    219
#define IDB_BAZA_OFF                    220
#define IDB_BAZA_ON                     221
#define IDB_BAZA_KOL                    222
#define IDB_BAZA_EM                     223
#define IDB_DOP_OFF                     224
#define IDB_DOP_ON                      225
#define IDB_DOP_EM                      226
#define IDB_EM_ON                       227
#define IDB_EM_BAZA                     228
#define IDB_EM_DOP                      229
#define IDB_EM_BAZA_DOP                 230
#define IDB_EM1KOM_BAZA                 231
#define IDB_KNOT_A                      232
#define IDB_KNOT                        233
#define IDB_KNOT_B                      234
#define IDB_KNOT_C                      235
#define IDB_KNOT_D                      236
#define IDB_KNOT_E                      237
#define IDB_KNOT_G                      238
#define IDB_KNOT_K                      239
#define IDB_KNOT_S                      240
#define IDB_EM_COMMON                   240
#define IDB_ANG                         241
#define IDB_ANG_B_K                     242
#define IDB_GNEZDO_C                    242
#define IDB_ANG_B_E                     243
#define IDB_GNEZDO_B                    243
#define IDB_ANG_B_E1KOM                 244
#define IDB_GNEZDO_S                    244
#define IDB_ANG_D_E                     245
#define IDB_GNEZDO_E                    245
#define IDB_BITMAPCIRCUIT               246
#define IDB_BAZA_EM1KOM_DOP             247
#define IDB_GATE_OFF                    248
#define IDB_GATE_ON                     249
#define IDB_GATE_KOL                    250
#define IDB_GATE_EM                     251
#define IDD_TESTRENAME_DLG              252
#define IDB_TESTRENAME                  253
#define IDI_ICON_HIGHU                  254
#define IDI_ICON_NOHIGHU                255
#define IDB_BITMAP_LEFTD                256
#define IDB_BITMAP_LEFTU                257
#define IDB_BITMAP_RESETD               258
#define IDB_BITMAP_RESETU               259
#define IDB_BITMAP_RIGHTD               260
#define IDB_BITMAP_RIGHTU               261
#define IDD_TABLDLG                     262
#define IDD_SAVETAB_DLG                 263
#define IDI_ICON_INVERSION_Y            264
#define IDD_SAVEREF_DLG                 265
#define IDD_FREEMEMORY_DLG              266
#define IDR_MENUFLOATINGTABL            267
#define IDB_BITMAP_NULL_CENTER          268
#define IDB_BITMAP_NULL_LEFT            269
#define IDB_BITMAP_NULL_RIGHT           270
#define IDI_ICON_TIPIMP1POSITIVE        271
#define IDI_ICON_TIPIMP1NEGATIVE        272
#define IDD_DEL_TST_DLG                 275
#define IDD_SAVETST_DLG                 276
#define IDD_SCALE_DLG                   279
#define IDB_BITMAP_MEMORY               280
#define IDB_BITMAP_KEY                  281
#define IDD_FILE_DIALOG                 282
#define IDI_ICON_EXPLORER               283
#define IDI_ICON_FILE                   284
#define IDI_ICON_MOD                    284
#define IDI_ICON_GRAPH1                 286
#define IDI_ICON_LIBRARY                287
#define IDD_SAVEOTCH_DLG                289
#define IDI_ICON_OTCH                   290
#define IDI_ICON_REF                    291
#define IDI_ICON_TXT                    292
#define IDI_ICON_XLS                    293
#define IDI_ICON_PART                   294
#define IDD_COPYFILE_DLG                295
#define IDI_ICON_MYCOMP                 296
#define IDI_ICON_EXE                    297
#define IDD_INFOCOPYFILE_DLG            298
#define IDI_ICON_FOLDER                 300
#define IDI_ICON_HELP                   302
#define IDD_HELP_DLG                    303
#define IDI_ICON_SHOOTDOWN              304
#define IDI_ICON_NET                    305
#define IDI_ICON_SWITCH                 306
#define IDI_ICON_USB                    307
#define IDD_KLAVA_DIALOG                308
#define IDI_ICON_LUPA                   310
#define IDD_LUPA_DLG                    311
#define IDD_KALIBR_DLG                  312
#define IDI_ICON_KALIBR                 314
#define IDB_BITMAP_MEMORY_FULL          315
#define IDD_AUTOSETNULL_DLG             316
#define IDB_KOL_OFF_BAZA                317
#define IDB_BITMAP_CXEMA1               318
#define IDB_BITMAP_CXEMA2               319
#define IDB_BITMAP_CXEMA3               320
#define IDB_BITMAP_CXEMA4               321
#define IDD_TABL_KOEF_DLG               322
#define IDD_VALENTER_DLG                323
#define IDD_IP_DLG                      324
#define IDI_ICON_DCPOSITIVE             325
#define IDI_ICON_DCNEGATIVE             326
#define IDI_ICON_CONSTPOSITIVE          327
#define IDI_ICON_CONSTNEGATIVE          328
#define IDB_EM_OFF                      329
#define IDI_ICON_LOOPING                330
#define IDI_ICON_FAMILY                 331
#define IDI_ICON_VKL                    332
#define IDI_ICON_IMP2POSITIVE           333
#define IDI_ICON_IMP2NEGATIVE           334
#define IDD_MODIFICATION_DLG            335
#define IDD_DIFF_DLG                    336
#define IDB_BITMAP_CXEMA5               337
#define IDC_VIEW_TREE                   1001
#define IDC_BUTTON_FILE                 1001
#define IDC_BUTTON_PARAM                1002
#define IDC_BUTTON_PANEL                1002
#define IDC_BUTTON_TUNING               1002
#define IDC_BUTTON_REF                  1003
#define IDC_BUTTON_MEMORY               1003
#define IDC_VIEW_TABL                   1004
#define IDC_BUTTON_TABL                 1004
#define IDC_BUTTON_GRAF                 1004
#define IDC_VIEW_OTCHT                  1005
#define IDC_BUTTON_OTCHT                1005
#define IDC_BUTTON_EXPLORER             1006
#define IDC_BUTTON_TEST                 1006
#define IDC_BUTTON_EXIT                 1007
#define IDC_BUTTON_RESET                1007
#define IDC_EDDATE                      1008
#define IDC_EDTIME                      1010
#define IDC_EDINFO                      1011
#define IDC_EDMODEL                     1012
#define IDC_EDINFOMEAS                  1013
#define IDC_EDINFOSIGNAL                1014
#define IDC_STATICMIGGREEN              1015
#define IDC_STATICMIGSIGNAL             1016
#define IDC_TABCTRLPARAM                1017
#define IDC_TABCTRLTUNING               1018
#define IDC_STATICNOMIGSIGNAL           1020
#define IDC_EDPAROLOLD                  1021
#define IDC_EDPAROLNEW                  1022
#define IDC_EDPAROLNEW1                 1023
#define IDC_EDPAROL                     1024
#define IDC_EDFILENAME                  1025
#define IDC_BUTPATH                     1026
#define IDC_CHECK1                      1027
#define IDC_TREE1                       1029
#define IDC_EDFILE                      1030
#define IDC_COMBOEL                     1031
#define IDC_COMBOMOD                    1032
#define IDC_EDITPRIM                    1033
#define IDC_BUTADD                      1034
#define IDC_RADIO_DIOD                  1036
#define IDC_RADIO_RES                   1037
#define IDC_RADIO_NPN                   1039
#define IDC_RADIO_PNP                   1040
#define IDC_RADIO_NMOS                  1042
#define IDC_RADIO_NPN4                  1043
#define IDC_RADIO_PNP4                  1044
#define IDC_RADIO_NMOS4                 1045
#define IDC_RADIO_PMOS                  1046
#define IDC_RADIO_PMOS4                 1047
#define IDC_STATICBITMAP_DIOD           1049
#define IDC_STATICBITMAP_RES            1050
#define IDC_STATICBITMAP_NPN            1051
#define IDC_STATICBITMAP_PNP            1052
#define IDC_STATICBITMAP_NMOS           1053
#define IDC_STATICBITMAP_PMOS           1054
#define IDC_STATICBITMAP_NPN4           1055
#define IDC_STATICBITMAP_PNP4           1056
#define IDC_STATICBITMAP_NMOS4          1057
#define IDC_STATICBITMAP_PMOS4          1058
#define IDC_STATIC_CATEGORIA            1059
#define IDC_EDITKNOT_KOL                1061
#define IDC_EDITKNOTKOL                 1061
#define IDC_EDITKNOT_BAZA               1062
#define IDC_EDITKNOTBAZA                1062
#define IDC_EDITKNOT_DOP                1063
#define IDC_EDITKNOTDOP                 1063
#define IDC_EDITKNOT_EM                 1064
#define IDC_EDITKNOTEM                  1064
#define IDC_COMBOCHECKKOL               1065
#define IDC_COMBOCHECKBAZA              1066
#define IDC_COMBOCHECKDOP               1067
#define IDC_TEXTCOMBOCHECKEM            1068
#define IDC_STATICKNOT                  1069
#define IDC_BUTTON_DIOD                 1070
#define IDC_BUTTON_RES                  1071
#define IDC_BUTTON_NPN                  1072
#define IDC_BUTTON_PNP                  1073
#define IDC_BUTTON_NMOS                 1074
#define IDC_BUTTON_PMOS                 1075
#define IDC_BUTTON_NPN4                 1076
#define IDC_BUTTON_PNP4                 1077
#define IDC_BUTTON_NMOS4                1078
#define IDC_BUTTON_PMOS4                1079
#define IDC_STATICBITMAP_DIOD_ON        1081
#define IDC_STATICBITMAP_RES_ON         1082
#define IDC_STATICBITMAP_NPN_ON         1083
#define IDC_STATICBITMAP_PNP_ON         1084
#define IDC_STATICBITMAP_NMOS_ON        1085
#define IDC_STATICBITMAP_PMOS_ON        1086
#define IDC_STATICBITMAP_NPN4_ON        1087
#define IDC_STATICBITMAP_PNP4_ON        1088
#define IDC_STATICBITMAP_NMOS4_ON       1089
#define IDC_STATICBITMAP_PMOS4_ON       1090
#define IDC_STATIC_ELEMENT              1091
#define IDC_STATICMOD                   1093
#define IDC_BUTTON_TEST_OK              1094
#define IDC_BUTTON_LOADTST              1095
#define IDC_RADIO_RAZVIMPPOSITIVE       1096
#define IDC_RADIO_RAZVDCPOSITIVE        1097
#define IDC_RADIO_RAZVAC                1098
#define IDC_RADIO_RAZVDCNEGATIVE        1099
#define IDC_RADIO_RAZVIMPNEGATIVE       1100
#define IDC_STATICIMPPOSITIVE           1101
#define IDC_STATICAC                    1102
#define IDC_STATICIMPNEGATIVE           1103
#define IDC_STATICRAZV                  1104
#define IDC_STATICDLITIMP               1105
#define IDC_COMBODLITIMP                1106
#define IDC_STATICDLITPAUZA             1107
#define IDC_EDITDLITPAUZA               1108
#define IDC_STATICIMP                   1109
#define IDC_EDKOLMEASU                  1110
#define IDC_EDKOLMEASI                  1111
#define IDC_COMBOKOLU                   1112
#define IDC_COMBOKOLI                   1113
#define IDC_STATICKOLMEAS               1114
#define IDC_EDKOLSOURCEU                1115
#define IDC_COMBOKOLSOURU               1116
#define IDC_STATICKOLLECTORSOURCE       1117
#define IDC_EDSLIDERKOLU                1118
#define IDC_SLIDERKOLU                  1119
#define IDC_TEXTRANGMINKOLU             1120
#define IDC_TEXTRANGMAXKOLU             1121
#define IDC_EDITLIMITKOLU               1122
#define IDC_EDSLIDERKOLI                1123
#define IDC_SLIDERKOLI                  1124
#define IDC_TEXTRANGMINKOLI             1125
#define IDC_EDTEXTRANGMAXKOLI           1126
#define IDC_EDITLIMITKOLI               1127
#define IDC_STATICLIMIT                 1128
#define IDC_CHECKKOLREJHIGH             1129
#define IDC_EDBAZASOURCEUI              1130
#define IDC_RADIOBAZASOURCEU            1131
#define IDC_RADIOBAZASOURCEI            1132
#define IDC_TEXTAMPLITUDEBAZA           1133
#define IDC_COMBOAMPLITUDEBAZA          1134
#define IDC_TEXTSTEPBAZA                1135
#define IDC_EDITSTEPBAZA                1136
#define IDC_SPINSTEPBAZA                1137
#define IDC_TEXTPOLARITYSTEP            1138
#define IDC_COMBOPOLARITYSTEP           1139
#define IDC_TEXTRANGBAZABIAS            1140
#define IDC_COMBORANGBAZABIAS           1141
#define IDC_SLIDERBAZABIAS              1142
#define IDC_TEXTMINBAZABIAS             1143
#define IDC_TEXTMAXBAZABIAS             1144
#define IDC_TEXTPOLARITYBIAS            1145
#define IDC_COMBOPOLARITYBAZABIAS       1146
#define IDC_EDITBAZABIAS                1147
#define IDC_STATICBAZABIAS              1148
#define IDC_STATICBAZA                  1149
#define IDC_EDMEASBAZA                  1150
#define IDC_RADIOMEASBAZAU              1151
#define IDC_RADIOMEASBAZAI              1152
#define IDC_TEXTRANGLIMITBAZA           1153
#define IDC_COMBOBAZALIMITMAXUI         1154
#define IDC_SLIDERLIMITBAZA             1156
#define IDC_EDITLIMITBAZA               1157
#define IDC_TEXTMINLIMITBAZA            1158
#define IDC_TEXTMAXLIMITBAZA            1159
#define IDC_STATICLIMITBAZA             1160
#define IDC_CHECKBAZAREJHIGH            1161
#define IDC_EDDOPSOURCEUI               1162
#define IDC_RADIODOPSOURCEU             1163
#define IDC_RADIODOPSOURCEI             1164
#define IDC_TEXTAMPLITUDEDOP            1165
#define IDC_COMBOAMPLITUDEDOP           1166
#define IDC_TEXTSTEPDOP                 1167
#define IDC_EDITSTEPDOP                 1168
#define IDC_SPINSTEPDOP                 1169
#define IDC_TEXTPOLARITYSTEPDOP         1170
#define IDC_COMBOPOLARITYSTEPDOP        1171
#define IDC_TEXTRANGDOPBIAS             1172
#define IDC_COMBORANGDOPBIAS            1173
#define IDC_SLIDERDOPBIAS               1174
#define IDC_EDITDOPBIAS                 1175
#define IDC_TEXTMINDOPBIAS              1176
#define IDC_TEXTMAXDOPBIAS              1177
#define IDC_TEXTPOLARITYBIASDOP         1178
#define IDC_COMBOPOLARITYDOPBIAS        1179
#define IDC_STATICDOPBIAS               1180
#define IDC_STATICDOP                   1181
#define IDC_EDMEASDOP                   1183
#define IDC_RADIOMEASDOPU               1184
#define IDC_RADIOMEASDOPI               1185
#define IDC_TEXTRANGLIMITDOP            1186
#define IDC_COMBODOPLIMITMAXUI          1187
#define IDC_SLIDERLIMITDOP              1188
#define IDC_EDITLIMITDOP                1189
#define IDC_TEXTMINLIMITDOP             1190
#define IDC_TEXTMAXLIMITDOP             1191
#define IDC_STATICLIMITDOP              1192
#define IDC_AXISY                       1193
#define IDC_FORMULA                     1194
#define IDC_AXISX                       1195
#define IDC_ENDFORMULA                  1196
#define IDC_ZONACHARACTERISTIC          1197
#define IDC_STATICREJX                  1198
#define IDC_STATICREJY                  1199
#define IDC_COMBOREJX                   1200
#define IDC_COMBOREJY                   1201
#define IDC_ZONAREJAXES                 1202
#define IDC_TEXTFIND                    1203
#define IDC_EDITNAMEPAR                 1204
#define IDC_TEXTFOR                     1205
#define IDC_EDITNAMEARG                 1206
#define IDC_TEXTPOINT                   1207
#define IDC_EDITPOINT                   1208
#define IDC_TEXT                        1209
#define IDC_TEXTUR1                     1210
#define IDC_TEXTUR2                     1211
#define IDC_EDITUR1                     1212
#define IDC_EDITUR2                     1213
#define IDC_RADIO1                      1214
#define IDC_RADIO2                      1215
#define IDC_ICONRADIO1                  1216
#define IDC_ICONRADIO2                  1217
#define IDC_ZONAFORMULA                 1218
#define IDC_TEXTMIN                     1219
#define IDC_TEXTMAX                     1220
#define IDC_EDITMIN                     1221
#define IDC_EDITMAX                     1222
#define IDC_STATICPOROG                 1223
#define IDC_ZONAPARAM                   1224
#define IDC_STATICZONATEXT              1226
#define IDC_BITMAP_U                    1227
#define IDC_BITMAP_I                    1228
#define IDC_STATIC_NULL_LEFT            1229
#define IDC_STATIC_NULL_CENTER          1230
#define IDC_STATIC_NULL_RIGHT           1231
#define IDC_STATIC_BUT_OFF_LEFT         1232
#define IDC_STATIC_BUT_OFF_CENTER       1233
#define IDC_STATIC_BUT_OFF_RIGHT        1234
#define IDC_STATIC_BUT_ON_LEFT          1235
#define IDC_STATIC_BUT_ON_CENTER        1236
#define IDC_STATIC_BUT_ON_RIGHT         1237
#define IDC_STATIC_BUT_INVERS_OFF       1238
#define IDC_STATIC_BUT_INVERS_ON        1239
#define IDC_STATIC_ICON_INVERS          1240
#define IDC_STATIC_MARKER_RESET         1241
#define IDC_STATIC_MARKER1              1242
#define IDC_STATIC_MARKER2              1243
#define IDC_STATIC_MARKER_LEFT          1244
#define IDC_STATIC_MARKER_RIGHT         1245
#define IDC_STATIC_MARKER1_ON           1246
#define IDC_STATIC_MARKER2_ON           1247
#define IDC_BUTTON_LEFT                 1249
#define IDC_BUTTON_RIGHT                1250
#define IDC_STATIC_TEXT_MARKER1         1251
#define IDC_STATIC_TEXT_MARKER2         1252
#define IDC_STATIC_BUTTON_TANGENT       1253
#define IDC_STATIC_BUTTON_TANGENT_ON    1254
#define IDC_STATIC_TEXT_TANGENT         1255
#define IDC_BUTTON_MARKER_RESET         1256
#define IDC_EDITERRORS                  1257
#define IDC_BUTTON_CONTROL_PARAM        1258
#define IDC_STATICINFOTEST              1260
#define IDC_EDITOTCHT                   1261
#define IDC_EDITPART                    1262
#define IDC_EDITPLAST                   1263
#define IDC_EDITFIO                     1265
#define IDC_EDITPOST                    1266
#define IDC_COMBONAMEEL                 1268
#define IDC_EDITNAMETEST                1269
#define IDC_EDITTEXTPRIM                1270
#define IDC_STATICBITBAZAKOL            1273
#define IDC_STATUS_EM_BAZA_DOP          1273
#define IDC_STATICBITKOL                1274
#define IDC_STATUS_EM1KOM_BAZA          1274
#define IDC_STATICBITBAZA               1276
#define IDC_STATUS_EM_DOP               1276
#define IDC_STATICBITELEMENT            1277
#define IDC_STATICBITDOP                1278
#define IDC_STATUS_DOP_ON               1278
#define IDC_STATICBITBAZAEM             1280
#define IDC_STATUS_EM_BAZA              1280
#define IDC_STATICBITEM                 1281
#define IDC_STATUS_EM_ON                1281
#define IDC_STATICBITDOPEM              1282
#define IDC_STATUS_DOP_EM               1282
#define IDC_STATICBITKNOTEM             1283
#define IDC_STATICBITANG                1284
#define IDC_STATICBIT_OFF               1284
#define IDC_STATUS_GATE_EM              1285
#define IDC_STATICBITKNOT_OFF           1286
#define IDC_STATICBITKNOT_A             1287
#define IDC_STATICBITKNOT_B             1288
#define IDC_STATICBITKNOT_C             1289
#define IDC_STATICBITKNOT_D             1290
#define IDC_STATICBITKNOT_E             1291
#define IDC_STATICBITKNOT_G             1292
#define IDC_STATICBITKNOT_K             1293
#define IDC_STATICBITKNOT_S             1294
#define IDC_STATICBITEM_COMMON          1294
#define IDC_STATICBITELEMENT_DIOD       1295
#define IDC_STATICBITELEMENT_RES        1296
#define IDC_STATICBITELEMENT_NPN        1297
#define IDC_STATICBITELEMENT_PNP        1298
#define IDC_STATICBITELEMENT_NMOS       1299
#define IDC_STATICBITELEMENT_PMOS       1300
#define IDC_STATICBITELEMENT_NPN4       1301
#define IDC_STATICBITELEMENT_PNP4       1302
#define IDC_STATICBITELEMENT_NMOS4      1303
#define IDC_STATICBITELEMENT_PMOS4      1304
#define IDC_STATICBIT_B_K               1305
#define IDC_STATICGNEZDO_C              1305
#define IDC_STATICBIT_B_E               1306
#define IDC_STATICGNEZDO_B              1306
#define IDC_STATICBIT_B_E1KOM           1307
#define IDC_STATICGNEZDO_S              1307
#define IDC_STATICBIT_D_E               1308
#define IDC_STATICGNEZDO_E              1308
#define IDC_STATUS_KOL_OFF              1309
#define IDC_STATUS_KOL_ON               1310
#define IDC_STATUS_KOL_BAZA             1311
#define IDC_STATUS_BAZA_OFF             1312
#define IDC_STATUS_BAZA_ON              1313
#define IDC_STATUS_BAZA_KOL             1314
#define IDC_STATUS_BAZA_EM              1315
#define IDC_STATUS_DOP_OFF              1316
#define IDC_STATICTEXTPAGE0             1317
#define IDC_STATUS_BAZA_EM1KOM_DOP      1318
#define IDC_STATUS_GATE_OFF             1326
#define IDC_STATUS_GATE_ON              1327
#define IDC_STATUS_GATE_KOL             1328
#define IDC_EDIT_NAMEEL                 1330
#define IDC_EDIT_NAMETEST               1331
#define IDC_EDIT_NEWPRIM                1332
#define IDC_OK                          1333
#define IDC_STATICEDDATE                1334
#define IDC_STATICEDINFO                1335
#define IDC_STATICEDTIME                1336
#define IDC_STATICHIGHU                 1337
#define IDC_STATICNOHIGHU               1338
#define IDC_MARKER1                     1339
#define IDC_MARKER2                     1340
#define IDC_TANGENT                     1341
#define IDC_LISTREF                     1342
#define IDC_LISTRES                     1343
#define IDC_BUTSAVETABRES               1344
#define IDC_STATIC_INFOTEST             1345
#define IDC_STATIC_SPOSOB               1347
#define IDC_RADIOADDDAT                 1348
#define IDC_RADIOREMOVEDAT              1349
#define IDC_EDITDISPLAYMEAS             1350
#define IDC_STATIC_INVERSY_OFF          1351
#define IDC_STATIC_INVERSY_ON           1352
#define IDC_STATIC_TEXT_INVERSY         1353
#define IDC_EDITDISPLAYREF              1354
#define IDC_STATICTEXT                  1355
#define IDC_EDITNAMEFILEREF             1356
#define IDC_STATICTEXTPRIMREF           1357
#define IDC_EDITPRIMREF                 1358
#define IDC_STATIC_RAMKA                1359
#define IDC_STATICBITMAPCIRCUIT         1360
#define IDC_PROGRESS1                   1361
#define IDC_PROGRESS_FREE_MEMORY        1361
#define IDC_PROGRESS                    1363
#define IDC_ST_FREEMEMORY               1364
#define IDC_CHECK_BAZA_VKL              1365
#define IDC_CHECK_DOP_VKL               1366
#define IDC_COMBO_PERIOD                1367
#define IDC_STATIC_FON                  1368
#define IDC_RADIO_LEFT                  1369
#define IDC_RADIO_CENTER                1370
#define IDC_RADIO_RIGHT                 1371
#define IDC_CHECK_INVERS_X              1372
#define IDC_CHECK_INVERS_Y              1373
#define IDC_RADIODOPU                   1374
#define IDC_RADIODOPI                   1375
#define IDC_EDITDLITIMP                 1376
#define IDC_RADIOTIPIMP                 1377
#define IDC_RADIOTIPIMP1                1378
#define IDC_STATICTIPIMP                1379
#define IDC_STATICTIPIMP1               1380
#define IDC_CHECKPAUZA                  1381
#define IDC_STATICTIPIMPNEG             1382
#define IDC_STATICTIPIMP1NEG            1383
#define IDC_STATICIMP1POS               1384
#define IDC_STATICIMP1NEG               1385
#define IDC_LIST_RESULT                 1387
#define IDC_TREE_TEST                   1388
#define IDC_STATIC_NAMEFILE             1389
#define IDC_STATIC_NAME_MARKER1         1390
#define IDC_STATIC_NAME_MARKER2         1391
#define IDC_STATIC_NAME                 1393
#define IDC_EDIT_NAME                   1394
#define IDC_STATIC_PRIM                 1395
#define IDC_EDIT_PRIM                   1396
#define IDC_STATIC_TEXT                 1397
#define IDC_EDIT_FILE                   1398
#define IDC_LIST_FILE_TST               1401
#define IDC_COMBO_EL                    1402
#define IDC_BUTTON_DEL                  1404
#define IDC_BUTTON_DEL_ALL              1405
#define IDC_STATIC_EL                   1406
#define IDC_STATIC_TEST                 1407
#define IDC_CHECK_INVERSION             1408
#define IDC_STATIC_MEMORY               1425
#define IDC_STATIC_KEY                  1426
#define IDC_STATICICON                  1427
#define IDC_EDITRANGBAZABIAS            1428
#define IDC_EDITRANGDOPBIAS             1429
#define IDC_STATIC_ICON                 1430
#define IDC_LIST_FILE                   1431
#define IDC_EDIT1                       1432
#define IDC_STATIC_TYPE                 1433
#define IDC_COMBO1                      1435
#define IDC_STATIC_TITLE                1437
#define IDC_CHECK_ZASCH_PAROL           1438
#define IDC_STATIC_GRAPH                1439
#define IDC_EDIT_NAME_REF               1440
#define IDC_BUTTON_DELETE               1443
#define IDC_STATIC_FILE                 1444
#define IDC_STATIC_FIO                  1445
#define IDC_STATIC_POST                 1446
#define IDC_EDIT_FIO                    1449
#define IDC_EDIT_POST                   1450
#define IDC_STATIC_PRODUCT              1451
#define IDC_EDIT_PRODUCT                1452
#define IDC_BUTTONPATH                  1453
#define IDC_BUTTON_PATH                 1454
#define IDC_CANCEL                      1457
#define IDC_STATIC_TEXT_USB             1458
#define IDC_STATIC_TEXT_DISK            1459
#define IDC_LIST_USB                    1460
#define IDC_LIST_DISK                   1461
#define IDC_STATIC_TIP                  1462
#define IDC_COMBO_FILTER                1463
#define IDC_BUTTON_MOVE                 1464
#define IDC_STATIC_FROM                 1465
#define IDC_EDIT_TO                     1466
#define IDC_EDIT_FROM                   1467
#define IDC_STATIC_ICON_FROM            1468
#define IDC_STATIC_ICON_TO              1469
#define IDC_STATIC_HELP                 1471
#define IDC_EDIT_HELP                   1472
#define IDC_STATIC_ICON_EXIT            1473
#define IDC_STATIC_ICON_NET             1474
#define IDC_STATIC_TEXT_NET             1475
#define IDC_STATIC_ICON_SWITCH          1476
#define IDC_STATIC_ICON_USB             1477
#define IDC_CHECK_LOOPING               1478
#define IDC_STATIC_LOOPING              1479
#define IDC_BTN_ESC                     1480
#define IDC_BTN_SHIFT                   1481
#define IDC_BTN_CAPSLOCK                1482
#define IDC_BTN_LANGUAGE                1483
#define IDC_BTN_PROBEL                  1484
#define IDC_BTN_BACKSPACE               1485
#define IDC_BTN_123                     1486
#define IDC_BTN_Q1                      1487
#define IDC_BTN_W1                      1488
#define IDC_BTN_E1                      1489
#define IDC_BTN_R1                      1490
#define IDC_BTN_T1                      1491
#define IDC_BTN_Y1                      1492
#define IDC_BTN_U1                      1493
#define IDC_BTN_I1                      1494
#define IDC_BTN_O1                      1495
#define IDC_BTN_P1                      1496
#define IDC_BTN_FSK1                    1497
#define IDC_BTN_FSK2                    1498
#define IDC_BTN_A1                      1499
#define IDC_BTN_S1                      1500
#define IDC_BTN_D1                      1501
#define IDC_BTN_F                       1502
#define IDC_BTN_G1                      1503
#define IDC_BTN_H1                      1504
#define IDC_BTN_J1                      1505
#define IDC_BTN_K1                      1506
#define IDC_BTN_L1                      1507
#define IDC_BTN_Z1                      1508
#define IDC_BTN_X1                      1509
#define IDC_BTN_INCLINE                 1510
#define IDC_BTN_C1                      1511
#define IDC_BTN_V1                      1512
#define IDC_BTN_B1                      1513
#define IDC_BTN_N1                      1514
#define IDC_BTN_M1                      1515
#define IDC_BTN_TZ                      1516
#define IDC_BTN_DVT                     1517
#define IDC_BTN_ZPT                     1518
#define IDC_BTN_THK                     1519
#define IDC_BTN_MINYS                   1520
#define IDC_BTN_PLUS1                   1521
#define IDC_EDITNAMEEL                  1522
#define IDC_COMBOCATEGORIA              1523
#define IDC_COMBO_SWITCH                1525
#define IDC_COMBONAKOPLENIE             1526
#define IDC_STATIC_ICON_LUPA            1527
#define IDC_STATIC_SCALEX               1528
#define IDC_STATIC_SCALEY               1529
#define IDC_TEXT_SCALEX                 1530
#define IDC_TEXT_SCALEY                 1531
#define IDC_STATIC_X_MIN                1532
#define IDC_STATIC_XMAX                 1533
#define IDC_STATIC_YMIN                 1534
#define IDC_STATIC_YMAX                 1535
#define IDC_EDIT_XMIN                   1536
#define IDC_EDIT_XMAX                   1537
#define IDC_EDIT_YMIN                   1538
#define IDC_EDIT_YMAX                   1539
#define IDC_STATIC_PRECISION            1540
#define IDC_EDIT_PRECISION              1541
#define IDC_SPIN_PRECISION              1542
#define IDC_TEXT_STEPX                  1543
#define IDC_TEXT_STEPY                  1544
#define IDC_EDIT_STEPX                  1545
#define IDC_EDIT_STEPY                  1546
#define IDC_STATIC_POINTS               1547
#define IDC_COMBO_POINTS                1548
#define IDC_EDIT_SERIAL                 1549
#define IDC_STATIC_DATEKALIBR           1550
#define IDC_EDIT_DATEKALIBR             1551
#define IDC_STATIC_MEMORY_FULL          1552
#define IDC_RADIO_ICM                   1553
#define IDC_RADIO_IBM                   1554
#define IDC_RADIO_UBM                   1555
#define IDC_RADIO_ISM                   1556
#define IDC_RADIO_UBS                   1557
#define IDC_RADIO_USS                   1558
#define IDC_RADIO_UCM                   1559
#define IDC_RADIO_IBS                   1560
#define IDC_RADIO_ISS                   1561
#define IDC_STATIC_2                    1562
#define IDC_STATIC_1                    1563
#define IDC_STATUS_KOL_OFF_BAZA         1564
#define IDC_COMBO_GNEZDO_C              1565
#define IDC_COMBO_GNEZDO_B              1566
#define IDC_COMBO_GNEZDO_E              1567
#define IDC_STATIC_GNEZDO_S             1569
#define IDC_COMBO_KOMMUTATOR            1570
#define IDC_STATIC_CXEMA1               1571
#define IDC_STATIC_CXEMA2               1572
#define IDC_STATIC_CXEMA3               1573
#define IDC_STATIC_CXEMA4               1574
#define IDC_RADIO_USM                   1575
#define IDC_STATIC_KANAL_C              1576
#define IDC_STATIC_KANAL_B              1577
#define IDC_STATIC_KANAL_S              1578
#define IDC_STATIC_MES                  1579
#define IDC_STATIC_INFO                 1580
#define IDC_PROGRESS_PROCESS            1581
#define IDC_STATIC_RANGE                1582
#define IDC_STATIC_VALUE_BIAS           1583
#define IDC_STATIC1                     1584
#define IDC_STATIC2                     1585
#define IDC_STATIC3                     1586
#define IDC_STATIC4                     1587
#define IDC_STATIC5                     1588
#define IDC_STATIC6                     1589
#define IDC_STATIC7                     1590
#define IDC_STATIC8                     1591
#define IDC_STATIC9                     1592
#define IDC_STATIC10                    1593
#define IDC_STATIC11                    1594
#define IDC_STATIC12                    1595
#define IDC_STATIC13                    1596
#define IDC_STATIC14                    1597
#define IDC_STATIC15                    1598
#define IDC_STATIC16                    1599
#define IDC_EDIT2                       1600
#define IDC_EDIT3                       1601
#define IDC_EDIT4                       1602
#define IDC_EDIT5                       1603
#define IDC_EDIT6                       1604
#define IDC_EDIT7                       1605
#define IDC_EDIT8                       1606
#define IDC_EDIT9                       1607
#define IDC_EDIT10                      1608
#define IDC_EDIT11                      1609
#define IDC_EDIT12                      1610
#define IDC_EDIT13                      1611
#define IDC_EDIT14                      1612
#define IDC_EDIT15                      1613
#define IDC_EDIT16                      1614
#define IDC_STATIC17                    1615
#define IDC_STATIC18                    1616
#define IDC_STATIC19                    1617
#define IDC_STATIC20                    1618
#define IDC_STATIC21                    1619
#define IDC_STATIC22                    1620
#define IDC_STATIC23                    1621
#define IDC_STATIC24                    1622
#define IDC_STATIC25                    1623
#define IDC_STATIC26                    1624
#define IDC_STATIC27                    1625
#define IDC_STATIC28                    1626
#define IDC_STATIC29                    1627
#define IDC_STATIC30                    1628
#define IDC_STATIC31                    1629
#define IDC_STATIC32                    1630
#define IDC_STATIC33                    1631
#define IDC_STATIC34                    1632
#define IDC_EDIT17                      1633
#define IDC_EDIT18                      1634
#define IDC_EDIT19                      1635
#define IDC_EDIT20                      1636
#define IDC_EDIT21                      1637
#define IDC_EDIT22                      1638
#define IDC_EDIT23                      1639
#define IDC_EDIT24                      1640
#define IDC_EDIT25                      1641
#define IDC_EDIT26                      1642
#define IDC_EDIT27                      1643
#define IDC_EDIT28                      1644
#define IDC_EDIT29                      1645
#define IDC_EDIT30                      1646
#define IDC_EDIT31                      1647
#define IDC_EDIT32                      1648
#define IDC_EDIT33                      1649
#define IDC_EDIT34                      1650
#define IDC_STATIC_RANGE1               1655
#define IDC_STATIC_VALUE1               1656
#define IDC_RADIO_CHANELC               1657
#define IDC_RADIO_CHANELB               1658
#define IDC_RADIO_CHANELS               1659
#define IDC_RADIO_IB                    1659
#define IDC_RADIO_MEAS                  1660
#define IDC_RADIO_SOURCE                1661
#define IDC_RADIO_I                     1662
#define IDC_RADIO_U                     1663
#define IDC_RADIO_BIAS                  1664
#define IDC_RADIO_COEF                  1665
#define IDC_BUTTON_SAVE                 1666
#define IDC_STATIC_KANALC               1667
#define IDC_STATIC_KANALB               1668
#define IDC_STATIC_KANALS               1669
#define IDC_BUTTON_APPLY                1671
#define IDC_STATIC_CHANEL_C             1677
#define IDC_RADIO_UB                    1678
#define IDC_RADIO_IS                    1679
#define IDC_RADIO_US                    1680
#define IDC_STATIC_CHANEL_B             1681
#define IDC_STATIC_CHANEL_S             1682
#define IDC_COMBO_RANGE                 1683
#define IDC_BUTTON_MEAS                 1684
#define IDC_EDIT_VALENTER               1685
#define IDC_STATIC_RAZM                 1686
#define IDC_STATIC_WHAT                 1687
#define IDC_EDIT_IP                     1688
#define IDC_STATIC_IP                   1689
#define IDC_RADIO_LBU                   1690
#define IDC_RADIO_LBI                   1691
#define IDC_RADIO_LDU                   1692
#define IDC_RADIO_LDI                   1693
#define IDC_RADIO_SYNPOSITIVE           1694
#define IDC_RADIO_SYNNEGATIVE           1695
#define IDC_STATICICONDCPOS             1696
#define IDC_STATICICONDCNEGATIVE        1697
#define IDC_STATICTIPDCPOS              1698
#define IDC_STATICTIPDCNEG              1699
#define IDC_STATICTIPAC                 1700
#define IDC_STATICREJIM                 1701
#define IDC_STATICCHANELC               1702
#define IDC_STATICCHANELB               1703
#define IDC_STATICTIPCONSTPOS           1704
#define IDC_STATICTIPCONSTNEG           1705
#define IDC_STATUS_EM_OFF               1706
#define IDC_STATICSTOP                  1707
#define IDC_STATICSTART                 1708
#define IDC_STATIC_ICON_LOOPING         1709
#define IDC_CHECK_FAMILY                1710
#define IDC_STATIC_ICON_FAMILY          1711
#define IDC_COMBO_QUE1                  1712
#define IDC_STATIC_QUE1                 1713
#define IDC_STATIC_VKL                  1714
#define IDC_STATICTIPIMP2               1715
#define IDC_STATICTIPIMP2NEG            1716
#define IDC_STATIC_MASK_VALUE           1717
#define IDC_STATIC_MASK                 1718
#define IDC_EDIT_NEW_IP                 1719
#define IDC_STATIC_NEW                  1720
#define IDC_RADIO3                      1721
#define IDC_RADIO_ICM_10N               1722
#define IDC_STATIC_CXEMA5               1723
#define IDR_FILE_NEW                    32771
#define IDR_FILE_OPEN                   32772
#define IDR_FILE_SAVE                   32773
#define IDR_FILE_SAVE_AS                32774
#define IDR_FILE_CLOSE                  32775
#define IDR_FILE_EXIT                   32776
#define IDR_FILE_REPAROL                32777
#define ID_ADDTREE1                     32778
#define ID_DEL                          32779
#define ID_RENAME                       32780
#define ID_COPY                         32781
#define ID_TST_STANDART                 32783
#define ID_TST_USER                     32784
#define ID_REF                          32786
#define ID_DEL_ALL                      32787
#define ID_PASTE                        32788
#define ID_MODIFY                       32789
#define ID_PARAM                        32791
#define ID_OTCHT                        32793
#define ID_OTCHT_NEW                    32794
#define ID_OTCHT_MAX                    32795
#define ID_OTCHT_SAVE                   32796
#define ID_OTCHT_MIN                    32797
#define ID_PART                         32799
#define ID_ZAPUSK_PUSK                  32800
#define ID_ZAPUSK_SIGNAL                32801
#define ID_MENUITEM32802                32802
#define ID_CURVE_LINE                   32803
#define ID_CURVE_POINT                  32804
#define ID_CURVE_LINEWITHPOINT          32805
#define ID_COLOR_FON                    32806
#define ID_COLOR_SETKA                  32807
#define ID_COLOR_FONT                   32808
#define ID_COLOR_CURVE                  32809
#define ID_COLOR_REF                    32810
#define ID_COLOR_TANGENT                32811
#define ID_SCALE_X                      32812
#define ID_SCALE_Y                      32813
#define ID_SAVE_BMP                     32814
#define ID_MENUITEM32815                32815
#define ID_OTCHT_MAIL                   32816
#define ID_KALIBR                       32817
#define ID_CONTROL                      32818
#define ID_TABL_COEF                    32818
#define ID_EXTRACT_REF                  32819
#define ID_DEL_MEMORY                   32820
#define ID_COPY_REF_TO_FLASH            32821
#define ID_COPY_MEMORY_FROM_FLASH       32822
#define ID_RESET_REF                    32823
#define ID_TABLMEAS                     32824
#define ID_ADD_TREEFROMPANEL            32825
#define ID_ADD_TREEFROMMEMORY           32826
#define ID_TEST_RENAME                  32827
#define ID_ZAPUSK_INTERNAL              32829
#define ID_ZAPUSK_EXTERNAL              32830
#define ID_SAVE_REF                     32831
#define ID_CLEAR_MEMORY                 32832
#define ID_LISTREF_CLOSE                32835
#define ID_LISTREF_OPEN                 32836
#define ID_FREEMEMORY                   32837
#define ID_REF_RESET                    32838
#define ID_OPENTABL                     32839
#define ID_SAVETABLREZ                  32840
#define ID_SOUND_ON                     32841
#define ID_SOUND_OFF                    32842
#define ID_TABL_MIN                     32843
#define ID_TABLRES_SAVE                 32844
#define ID_MARKER_AKT                   32845
#define ID_MARKER_NOAKT                 32846
#define ID_DEL_TST_STANDART             32848
#define ID_DEL_TST_USER                 32849
#define ID_SAVE_RESULT_ON               32850
#define ID_SAVE_RESULT_OFF              32851
#define IDC_MODIFY_IP_ADDRESS           32852
#define IDC_FILE_DELETE                 32853
#define IDR_TABL_DELETE                 32854
#define IDC_DELETE_OTCH                 32855
#define IDC_TUNING_COPYFILE             32856
#define ID_GRAF_LUPA                    32857
#define ID_AUTO_SETUP_NULL              32858
#define ID_POINT_SIZE_SMALL             32860
#define ID_POINT_SIZE_BIG               32861
#define ID_DIFFERENCE_VAX               32862

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32863
#define _APS_NEXT_CONTROL_VALUE         1724
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
